### ISSUE TITLE
Assembly file does not match cprops file. Exiting!

### ISSUE THREAD

**Issue by fwlei123** [aidenlab/3d-dna#102]
Hi,
I'm currently trying to use 3d-dna (version 180922) to assemble a bird genome. The run-asm-pipeline.sh pipeline ran and generate almost all the .hic files except split stage. And, I got the following error during split stage and sealing stage:
:( Assembly file does not match cprops file. Exiting!
:| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
:| Warning: No input for label2 was provided. Default for label2 is ":::debris"

the command i used were as follow:
nohup bash /home/software/3d-dna/run-asm-pipeline.sh --build-gapped-map 
/home/assembly/3d_dna/ref/duck.hifiasm.p_ctg.fa ../aligned/merged_nodups.txt
[code.txt](https://github.com/aidenlab/3d-dna/files/5981100/code.txt)
[nohup.txt](https://github.com/aidenlab/3d-dna/files/5981101/nohup.txt)

[duck.hifiasm.p_ctg.split.assembly.txt](https://github.com/aidenlab/3d-dna/files/5981108/duck.hifiasm.p_ctg.split.assembly.txt)
[duck.hifiasm.p_ctg.split.cprops.txt](https://github.com/aidenlab/3d-dna/files/5981113/duck.hifiasm.p_ctg.split.cprops.txt)
[goose.hifiasm.p_ctg.split.asm.txt](https://github.com/aidenlab/3d-dna/files/6026429/goose.hifiasm.p_ctg.split.asm.txt)
I checked the files in split stage and found that the .assembly file was different with .asm file.
Actually,the pipeline generate complete .final files and .FINAL files.
So, does this error fetal? 
Are there a way to resolve this problem?

Many thanks!

**Comment by xinghua1001** [comment]
I also got similar problem. Some of the hic file failed to be built and got errors like below. Waiting for some help

...Dumping 25000 resolution matrix
HiC file version: 8
Unable to dump
java.io.IOException: Normalization missing for: assembly_assembly_BP_25000
        at juicebox.data.DatasetReaderV2.readNormalizedBlock(DatasetReaderV2.java:719)
        at juicebox.data.MatrixZoomData.dump(MatrixZoomData.java:675)
        at juicebox.tools.clt.old.Dump.dumpMatrix(Dump.java:282)
        at juicebox.tools.clt.old.Dump.run(Dump.java:505)
        at juicebox.tools.HiCTools.main(HiCTools.java:86)
...Estimating necessary saturation level for requested misassembly sensitivity
...Coarse resolution saturation level = 
...Analyzing near-diagonal mismatches
...Filtering mismatch calls without better alternative: Not functional yet, skipping
...Thinning mismatch region boundaries.

**Comment by dudcha** [comment]
Hello Xinghua,

This appears to be a completely unrelated problem. The error is right there in the message you have sent: the contact matrix did not normalize at 25kb resolution. This usually means that there are some huge coverage issues, either due to contamination, or large blocks of undercollapsed heterozygosity, or this is a metagenome. Depending on the situation you might want to examine your sequences and remove outliers, or try to run the pipeline with NONE as your editor normalization (--editor-coarse-norm in latest release).

Best,
Olga

**Comment by dudcha** [comment]
Hi Fwlei123,

The error means that splitting into chromosomes failed. The easiest would probably be to split manually in JBAT if you are plannning to do revisions anyway. You'll see the split probably giving up half the way int he final.hic contact map annotations.

Best,
Olga

**Comment by zhaotao1987** [comment]
Hello Olga,
I came across the same problem today, but I'm just trying to generate a hic file from aligned bam for visualizing, like a format conversion task.
I'm following the manual from the bottom of  https://github.com/phasegenomics/juicebox_scripts.
![image](https://user-images.githubusercontent.com/16197676/163171961-00fc111e-75b2-4b01-95f0-f53617dec017.png)
```
INFO: converting bam to juicer on hic_reads.aligned.sorted.cleaned.bam
INFO: detected bam filetype
INFO: reading file "hic_reads.aligned.sorted.cleaned.bam"
INFO: parsed 1000000 read pairs
INFO: parsed 2000000 read pairs
INFO: parsed 3000000 read pairs
INFO: parsed 4000000 read pairs
:) -p flag was triggered. Running with GNU Parallel support parameter set to false.
...Remapping contact data from the original contig set to assembly
:( Assembly file does not match cprops file. Exiting!
...Building track files
:( Assembly file does not match cprops file. Exiting!
...Building the hic file
temp.hifi_psin.haps.fasta.asm_mnd.txt does not exist or does not contain any reads.
```
