### ISSUE TITLE
Uncertain error

### ISSUE THREAD

**Issue by yeswzc** [aidenlab/3d-dna#4]
Hi, I used my genome fasta file and the merged_nodups.txt file as input for scaffolding, but find errors:
java.lang.NumberFormatException: For input string: "scaffold3:::fragment_47"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.parseInt(Integer.java:615)
        at juicebox.tools.utils.original.AsciiPairIterator.advance(AsciiPairIterator.java:148)
        at juicebox.tools.utils.original.AsciiPairIterator.next(AsciiPairIterator.java:194)
        at juicebox.tools.utils.original.Preprocessor.computeWholeGenomeMatrix(Preprocessor.java:493)
        at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:371)
        at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:283)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:108)
        at juicebox.tools.HiCTools.main(HiCTools.java:86)
Could not read hic file: null
:( Juicebox dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
mv: cannot stat 'depletion_score_wide.wig': No such file or directory
mv: cannot stat 'depletion_score_narrow.wig': No such file or directory
mv: cannot stat 'mismatch_wide.bed': No such file or directory
mv: cannot stat 'mismatch_narrow.bed': No such file or directory

and repeated warnings:
:| Warning: No input for label1 was provided. Default for label1 is ":::fragment_"
:| Warning: No input for label2 was provided. Default for label2 is ":::debris"

Could anyone help?

**Comment by dudcha** [comment]
Hi,

Looks like building of the contact map (.hic file) has failed. Which step of the pipeline are you at? What does the line starting with scaffold3:::fragment_47 say in the .cprops file corresponding to this step?

Best,
Olga

**Comment by yeswzc** [comment]
I am not sure what stage I was in, I used the most easy way to run it: run-pipeline.sh -m diploid -s 3 -c 24 -t 10000 genome.fa merged_nodups.txt . The program is still runnning, will this scaffoding failed?
The 0.hic and 2.hic files seem OK, 1.hic, 3.hic and polished.hic file are almost empty now.
centos$ grep -h "fragment_47" *.cprops
It said:
scaffold3:::fragment_47 81 22887345
scaffold19:::fragment_47 373 5000
scaffold26:::fragment_47:::debris 480 23000
scaffold34:::fragment_47 599 36129
scaffold3:::fragment_47 81 22887345
scaffold19:::fragment_47 373 5000
scaffold26:::fragment_47:::debris 480 23000
scaffold34:::fragment_47 599 36129
scaffold19:::fragment_47 292 11000
scaffold3:::fragment_47 81 22887345
scaffold19:::fragment_47 373 5000
scaffold26:::fragment_47:::debris 480 23000
scaffold34:::fragment_47 599 36129

**Comment by yeswzc** [comment]
use -w -n parameter, and add -s number of steps.
This seems could solve.
