### ISSUE TITLE
java.lang.NumberFormatException

### ISSUE THREAD

**Issue by hung-th** [aidenlab/3d-dna#92]
Thank you for developing this useful package.

When I am running 3D-DNA, I encountered the below error:

```/data/dops-dalbergia/univ4423/bin/3d-dna/run-asm-pipeline.sh /data/dops-dalbergia/univ4423/DBCO/fc_phase_a80/5-phase/output/phased.0.fasta merged_nodups.txt
version: 180922
###############
Starting iterating scaffolding with editing:
...starting round 0 of scaffolding:
:) -p flag was triggered. Running LIGer with GNU Parallel support parameter set to true.
:) -s flag was triggered, starting calculations with 15000 threshold starting contig/scaffold size
:) -q flag was triggered, starting calculations with 1 threshold mapping quality
...Using cprops file: phased.0.0.cprops
...Using merged_nodups file: phased.0.mnd.0.txt
...Scaffolding all scaffolds and contigs greater or equal to 15000 bp.
...Starting iteration # 1
:) DONE!
...visualizing round 0 results:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -q flag was triggered, starting calculations for 1 threshold mapping quality
:) -i flag was triggered, building mapq without
:) -c flag was triggered, will remove temporary files after completion
...Remapping contact data from the original contig set to assembly
...Building track files
...Building the hic file
Not including fragment map
Start preprocess
Writing header
Writing body
java.lang.NumberFormatException: For input string: "R2"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:658)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at juicebox.tools.utils.original.AsciiPairIterator.advance(AsciiPairIterator.java:149)
	at juicebox.tools.utils.original.AsciiPairIterator.next(AsciiPairIterator.java:194)
	at juicebox.tools.utils.original.Preprocessor.computeWholeGenomeMatrix(Preprocessor.java:493)
	at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:371)
	at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:283)
	at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:108)
	at juicebox.tools.HiCTools.main(HiCTools.java:86)
...detecting misjoins in round 0 assembly:
:) -p flag was triggered. Running with GNU Parallel support parameter set to true.
:) -c flag was triggered, starting calculations with 5% saturation level
:) -w flag was triggered, performing cursory search for mismatches at 25000 resolution
:) -d flag was triggered, depletion score will be averaged across a region bounded by 125000 superdiagonal
:) -k flag was triggered, starting calculations with 55% depletion as mismatch threshold
:) -n flag was triggered, performing mismatch region thinning at 1000 resolution
...Dumping 25000 resolution matrix
HiC file version: 8
ERROR [2020-10-12 22:08:59,712]  [DatasetReaderV2.java:229] [main]  Error reading dataset
java.io.EOFException
	at htsjdk.tribble.util.LittleEndianInputStream.readString(LittleEndianInputStream.java:119)
	at juicebox.data.DatasetReaderV2.readFooter(DatasetReaderV2.java:435)
	at juicebox.data.DatasetReaderV2.read(DatasetReaderV2.java:225)
	at juicebox.data.HiCFileTools.extractDatasetForCLT(HiCFileTools.java:64)
	at juicebox.tools.clt.old.Dump.readArguments(Dump.java:353)
	at juicebox.tools.HiCTools.main(HiCTools.java:85)
Could not read hic file: null
:( Juicebox dump is empty! Perhaps something is wrong with the hic file or the requested resolution is too high. Exiting!
:) -w flag was triggered, performing cursory search for repeat at 25000 resolution
:) -t flag was triggered, flagging regions with coverage higher than 2
...Dumping 25000 resolution coverage track
HiC file version: 8
```

I am using java 1.8.0.

I would be really grateful for your time and help!

**Comment by dudcha** [comment]
Hello Henry,

There seems to be something wrong with your input. There are no interactions during scaffolding, the map error points to the same thing. Check your fasta and merged_nodups.txt files, that they actually match and that they are of expected format.

Thanks,
Olga

**Comment by hung-th** [comment]
Hi Olga, thank you for your reply.

`head merged_nodups.txt`

```
0 000000F_0 110 0 16 000000F_0 165 0 0 2S55M93S NCCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCAACCCTAAACCTGTCTCTTATACACATCTGACGCTGCCGACGAGTACCACAGTGTAGATCTCGGTGGTCGCCGTATCATTAAAAAAAAAACACAGGTTAGAACT 0 96S54M CCTTTGGAATACACAGGTAGTTTTTTTTCAAGCAGAAGACGGCATACGAGATAGCTAACCGTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCAACCCTAAAC GWNJ-0957:663:GW2009263402nd:1:1218:16924:1555 GWNJ-0957:663:GW2009263402nd:1:1218:16924:1555
0 000000F_0 1730 0 16 000000F_0 1912 0 0 150M CCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCAAAACCCAAAACCCTAAACCCTAAACCC 0 150M AACCCAAAACCCTACACCCAAAGCCCCAATCCCTTAACCCTAAACCCTAACCCCTAAACCCTACACCCTAAACCCTAAACCCTAAACCCAAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAAC GWNJ-0957:663:GW2009263402nd:1:1109:16315:69098 GWNJ-0957:663:GW2009263402nd:1:1109:16315:69098
0 000000F_0 1737 0 16 000000F_0 11269 0 0 150M CCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCAAAACCCTAAACCCTAAACCCTAAACCCTAAACCC 12 14S136M AACCCTGATGCCTGAACCCTAAGCCCTAAACCCTAAACCCTAAACCCTAAACCCTCAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAAC GWNJ-0957:663:GW2009263402nd:1:1108:30381:12279 GWNJ-0957:663:GW2009263402nd:1:1108:30381:12279
```

`grep ">" phased.0.fasta | head`

```
>000000F_0
>000001F_0
>000002F_0
>000003F_0
>000004F_0
>000005F_0
>000006F_0
>000007F_0
>000008F_0
>000009F_0
```

The fasta does not seem to have any problem. I am unsure of the format of merged_nodups.txt. Do you think it looks normal?

**Comment by dudcha** [comment]
Check for carriage return, i.e. look in an editor with hidden characters. -Olga

**Comment by hung-th** [comment]
My bad. The file system on my cluster is quite unstable these days, I just noticed there was a premature cp leading to a truncated merged_nodups.txt file. It is now running perfectly now. Thanks for your help.
